language: python
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
install:
  - pip install -r requirements.txt
  - pip install nose
  - pip install tox
script:
  - tox
